### ISSUE TITLE
Convert to compose multiplatform

### ISSUE THREAD

**Issue by fjr619** [patrickdip/KMM_SocialMediaApp#1]
It will be great if you can make compose multiplatform, instead of code 2 different platform (kotlin and swift)

**Comment by patrickdip** [comment]
After the Android and server components are fully completed, I'll create a poll for everyone to share their perspectives, and perhaps we'll consider making it a Compose multiplatform project. Nonetheless, I'm also preparing a Compose multiplatform tutorial after this series.
